### ISSUE TITLE
Starting apps with optirun

### ISSUE THREAD

**Issue by mlippie** [nicohman/eidolon#1]
First of all thanks, this is a great project!
Is it possible to run games with optirun from the launcher?

**Comment by nicohman** [comment]
Right now, it is not possible without recompiling the program altogether. When I get home today though, I’ll add a config option that lets you define a program to run games with, which could also work for launching certain games within the steam runtime. Thanks for bring this to my attention, though. I’ll add it in soon.

**Comment by mlippie** [comment]
Thanks, looking forward to it!

**Comment by nicohman** [comment]
Okay, added the 'prefix_command' option! There's also a new release published [here](https://github.com/nicohman/eidolon/releases) so you won't have to manually compile. Gonna close this now.
