### ISSUE TITLE
$XDG_CONFIG_HOME/eidolon/games//start: No such file or directory

### ISSUE THREAD

**Issue by egeesin** [nicohman/eidolon#2]
When I execute `eidolon menu` for the first time, I got this output:
```
[" $HOME/.local/share/steam/steamapps |"]

sh: /home/ege/.config/eidolon/games//start: No such file or directory
```
With default config, rofi menu appears but there's no list of my games.

**Comment by nicohman** [comment]
Hey, first off: have you run `eidolon update` yet? It needs to be run at least once for steam games to register. If you have, is your steam library location different from the default?

**Comment by egeesin** [comment]
Sorry, I didn't mention that I initially execute `eidolon update` because the menu command already told me so. Also there might be another problem. To reproduce the issue, I remove/install the package. But every command except `eidolon` and `eidolon help` gives me this output:
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /build/rust/src/rustc-1.22.1-src/src/liballoc/vec.rs:1552:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I don't know if I did something noob-ish during uninstallation or because of the code. All I did was `sudo rm -rf /usr/bin/eidolon` then repeating installation steps.

**Comment by nicohman** [comment]
Okay, can you remove $XDG_CONFIG_HOME/eidolon then try running `eidolon` once to init, then run `eidolon update` again? That should correctly start you fresh. I just tried installing it on a fresh machine, and it works fine, so I think something went wrong in installation. Also, addressing the len/index error message: That's just the error it throws when you aren't passing enough arguments to the command. E.g. if you're running `add` you need two more arguments, `name` and `location` or it will crash. I should probably make that message clearer.

**Comment by egeesin** [comment]
Okay, I figured out exactly when/why I get 'thread main panicked...' and ' ...games//start No such file...' outputs. Sorry for past comments, it has nothing to do with original issue. In default config, steam_dirs was set as ``$HOME/.local/share/``**``steam``**``/steamapps`` I don't have a directory called 'steam' but 'Steam'. After I changed to right one, update command worked succesfully. ``eidolon add "Super Tux Kart" "/bin/supertuxkart"`` worked too.

Other than, these outputs still occurs. When there's no new game to update from Steam library or if I type command/string wrong, I get "thread main panicked..." output. If I open the menu in terminal then close it or select a game, I get ".config/eidolon/games// start: No such file...". Fortunately, that doesn't prevent me from launching game, adding or updating database so far. Considering that I can bind a key for ``eidolon menu``, this issue isn't critical but just annoying. I think what's missing is informative outputs.

**Comment by nicohman** [comment]
Okay, I’ll see what I can do about removing the error message when not selecting a game. I have added a few more informative messages already, and I’ll see about clarifying more, including if the steam library is where it’s meant to be. Thanks for this, it’s been helpful showing where I need to improve.

**Comment by nicohman** [comment]
Okay, I've added a few QoL things here and there that should make pretty much all outputs way more informative. Feel free to download a pre-compiled binary [here](https://github.com/nicohman/eidolon/releases). Thanks for your feedback and don't hesitate to ask any more questions you might need!
