### ISSUE TITLE
Running as Rofi Modi

### ISSUE THREAD

**Issue by ibrokemypie** [nicohman/eidolon#6]
Are there any plans to allow running the menu as a rofi modi? 
This would allow launching the games directly from rofi without having to run another script, which would be awesome.

**Comment by nicohman** [comment]
I added a file name 'eidolon.sh' to the code. If you run rofi with `rofi -show eidolon -modi eidolon:[the path to the script]`, then you should be able to use eidolon in rofi.

**Comment by ibrokemypie** [comment]
Seems to crash/freeze my rofi when run as ``rofi -show games -modi games:./eidolon.sh```

**Comment by nicohman** [comment]
Can you try two things for me? Can you make sure eidolon.sh has the executable flag, and can you try using an absolute path like ~/Downloads/eidolon.sh instead of a relative path? Thanks!

**Comment by ibrokemypie** [comment]
Same thing. Should have clarified, the games list comes up and rofi works fine until I start a game. Mouse still moves and I can see the game start up but rofi freezes and at the same time captures all input (keyboard and mouse clicks)

**Comment by nicohman** [comment]
Oh, wow. Didn’t do that when I tried it before, I’ll tell you. Tried it now and it does do that. Pushed a commit though, can you try that one? It works for me now with this fix.

**Comment by ibrokemypie** [comment]
Confirmed that it now works, thanks!
