### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a sequence", line: 1, column: 4)', libcore/result.rs:1009:5

### ISSUE THREAD

**Issue by JasonB579** [nicohman/eidolon#8]
I got the error in the issue title when running `eidolon update` after it tries to read the itch.io games. I don't use itch.io, so I assume it has to do with the itch stuff not existing on my computer, but I don't know enough rust to debug this myself. I ran the command again with RUST_BACKTRACE=1 and got:

```
>>Reading in itch.io games
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a sequence", line: 1, column: 4)', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: butlerd::Butler::fetchall
  10: libeidolon::auto::update_itch
  11: eidolon::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
  17: __libc_start_main
  18: _start
```
I am running eidolon 1.4.4

**Comment by nicohman** [comment]
I pushed a commit that should detect this better, and doesn't display any errors on my machine without itch. Would you mind compiling master and checking whether it still prints out an error? Thanks!

**Comment by nicohman** [comment]
Hmm. That is very unusual. Just tested it on a new computer, and it throws nothing. It looks like it thinks that itch is installed, and is trying to contact it, but crashes when it doesn't get anything. If you remove the folder at ~/.config/eidolon, does it still throw this error? Do you have anything at ~/.config/itch, or do you have an executable named butler installed? Thanks and sorry for the inconvenience.

**Comment by nicohman** [comment]
Oh, that makes sense then. That was what was confusing eidolon so much. Butler is the itch client's daemon, so by having it but not the full client installed, it was acting strangely. Thanks for the report--I'll see if I can do something to stop this from happening in the future.
