### ISSUE TITLE
Trouble Adding DRM-Free Games

### ISSUE THREAD

**Issue by JasonB579** [nicohman/eidolon#9]
Based on what I've seen, I should be able to add native linux DRM-free games through the `eidolon import` command, but regardless of what directory I point it to it can't seem to find my games. Are there any tricks to this, like a specific directory structure, or, even better, is there a way I can get games from Lutris that aren't using the Steam or Wine runners?

**Comment by JasonB579** [comment]
Actually, I've forked this and I want to see if I can add a feature so that this can pull down all games in all runners from Lutris using `eidolon update`. I'd like to close this issue for now, as I'd like to see if I can add this feature.

**Comment by nicohman** [comment]
I know you said you wanted to code this, but just a note: You should be able to let eidolon pull from all lutris runners just by removing the line that filters for wine in `eidolon.rs`. Also, the import command is exceedingly weird and is meant to work mostly for GOG games or games from a very old version of eidolon that was written in nodejs. If you're just adding native games, I'd recommend using the basic add command. Thanks for contributing and helping make eidolon better.
